# Generated by Django 5.2.6 on 2025-10-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('personal_limit', models.IntegerField(default=5)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_of_Bureau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customer_logos/')),
                ('status', models.BooleanField(default=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Operations_App.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Personals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Operations_App.bureau')),
            ],
        ),
        migrations.AddField(
            model_name='bureau',
            name='representative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_representative', to='User_Operations_App.personals'),
        ),
    ]
